/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ALVA
 */
public class Interfaz3x3 extends javax.swing.JFrame {

    /**
     * Creates new form Interfas3x3
     */
    public Interfaz3x3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        casilla1 = new javax.swing.JButton();
        casilla2 = new javax.swing.JButton();
        casilla3 = new javax.swing.JButton();
        casilla4 = new javax.swing.JButton();
        casilla5 = new javax.swing.JButton();
        casilla6 = new javax.swing.JButton();
        casilla7 = new javax.swing.JButton();
        casilla8 = new javax.swing.JButton();
        casilla9 = new javax.swing.JButton();

        jButton13.setText("jButton10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        casilla1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(casilla1);

        casilla2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(casilla2);

        casilla3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(casilla3);

        casilla4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(casilla4);

        casilla5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(casilla5);

        casilla6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(casilla6);

        casilla7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(casilla7);

        casilla8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(casilla8);

        casilla9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(casilla9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz3x3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton casilla1;
    public javax.swing.JButton casilla2;
    public javax.swing.JButton casilla3;
    public javax.swing.JButton casilla4;
    public javax.swing.JButton casilla5;
    public javax.swing.JButton casilla6;
    public javax.swing.JButton casilla7;
    public javax.swing.JButton casilla8;
    public javax.swing.JButton casilla9;
    private javax.swing.JButton jButton13;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
